name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    paths:
    - '**.cs'
    - '**.cspro'
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running a build?'
        required: true
        default: 'Manual build'

env:
  DOTNET_VERSION: '6.0.100-preview.7.21379.14' # set this to the dot net version to use
  
jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: 'Print manual build reason'
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo 'Reason: ${{ github.event.inputs.reason }}'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install dependencies
      run: |
        cd ./SimpleRestApiQuestions
        dotnet restore
    
    - name: Build
      run: |
        cd ./SimpleRestApiQuestions
        dotnet build --configuration Release --no-restoremal
        
    - name: Test
      run: |
        cd ./TestRestApiQuestions
        dotnet test --no-restore --verbosity normal
