name: Build & Test 

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
         submodules: 'true'
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.7.21379.14
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Restore dependencies
      run: dotnet restore
      working-directory: SimpleRestApiQuestions
    - name: Build
      run: dotnet build --no-restore
      working-directory: SimpleRestApiQuestions
    - name: Test
      working-directory: SimpleRestApiQuestions
      run: dotnet test --no-build --verbosity normal